name: Java CI with Gradle

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
			- name: Setup JDK 11
				uses: actions/setup-java@v3
				with:
					java-version: '11'
					distribution: 'temurin'
