name: Java CI with Gradle

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Delete Gradle cache
      run: rm -rf $HOME/.gradle/caches
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with: 
        cache-disabled: true
    - name: Execute Gradle build
      run: ./gradlew --no-daemon clean build 
    # - name: Execute Gradle unit test
    #   run: ./gradlew test
    # - name: Build docker image
    #   run: ./gradlew --no-daemon jibDockerBuild
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
      