name: Java CI with Gradle

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with: 
        cache-disabled: true
    - name: Execute Gradle build
      run: ./gradlew --no-daemon clean build 
    - name: Execute Gradle unit test
      run: ./gradlew test
    - name: Build docker image
      run: ./gradlew --no-daemon jibDockerBuild
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push docker image
      run: ./gradlew --no-daemon dockerPush
      